variables:
    PROJECT_NAME: "ngbook-pub-tpl" # 该项目名
    DOCKER_HUB_NAME: "172.16.102.51:5002/dev" # docker registry地址
    CONTAINER_NAME: "pub-tpl-test" # 运行起来的docker容器名
    CONTAINER_PORT: 27545 # docker容器运行的端口号

before_script:
    - eval export VERSION=${CI_BUILD_REF:0:8}
    - eval export IMAGE=$PROJECT_NAME:$VERSION
    - eval export REMOTE_IMAGE=$DOCKER_HUB_NAME/$IMAGE

测试环境:
    type: deploy
    script:
        - echo "开始编译新镜像：${IMAGE} ..."
        - docker build -t $IMAGE .
        - docker tag $IMAGE $REMOTE_IMAGE
        - docker push $REMOTE_IMAGE
        - echo '新镜像已生成，开始部署到各目标机上...'
        - ansible-playbook deploy/deploy.yml -i deploy/hosts --extra-vars "ENV=test REMOTE_IMAGE=$REMOTE_IMAGE CONTAINER_NAME=$CONTAINER_NAME CONTAINER_PORT=$CONTAINER_PORT"
    only:
        - dev
    when: always
    tags:
        - runner-102-51
