variables:
    PROJECT_NAME: "ngbook-pub-tpl" # 该项目名
    DOCKER_HUB_REGISTRY: "ngbook" # docker registry地址或 docker hub用户名
    CONTAINER_NAME: "ngbook-pub-tpl" # 运行起来的docker容器名
    CONTAINER_PORT: 12345 # docker容器运行的端口号

before_script:
    - eval export VERSION=${CI_BUILD_REF:0:8}
    - eval export IMAGE=$PROJECT_NAME:$VERSION
    - eval export REMOTE_IMAGE=$DOCKER_HUB_REGISTRY/$IMAGE

测试环境:
    type: deploy
    script:
        - echo "开始编译新镜像：${IMAGE} ..."
        - docker build -t $IMAGE .
        - docker tag $IMAGE $REMOTE_IMAGE
        - docker push $REMOTE_IMAGE
        - echo '新镜像已生成，开始部署到各目标机上...'
        - ansible-playbook deploy/deploy.yml -i deploy/hosts --extra-vars "ENV=test REMOTE_IMAGE=$REMOTE_IMAGE CONTAINER_NAME=$CONTAINER_NAME CONTAINER_PORT=$CONTAINER_PORT"
    only:
        - test
    when: always
    tags:
        - frontend


QA环境:
    type: deploy
    script:
        - echo "开始编译新镜像：${IMAGE} ..."
        - docker build -t $IMAGE .
        - docker tag $IMAGE $REMOTE_IMAGE
        - docker push $REMOTE_IMAGE
        - echo '新镜像已生成，开始部署到各目标机上...'
        - ansible-playbook deploy/deploy.yml -i deploy/hosts --extra-vars "ENV=qa REMOTE_IMAGE=$REMOTE_IMAGE CONTAINER_NAME=$CONTAINER_NAME CONTAINER_PORT=$CONTAINER_PORT"
    only:
        - qa
    when: manual
    tags:
        - frontend


预发布环境:
    type: deploy
    script:
        - echo "开始编译新镜像：${IMAGE} ..."
        - docker build -t $IMAGE .
        - docker tag $IMAGE $REMOTE_IMAGE
        - docker push $REMOTE_IMAGE
        - echo '新镜像已生成，开始部署到各目标机上...'
        - ansible-playbook deploy/deploy.yml -i deploy/hosts --extra-vars "ENV=stg REMOTE_IMAGE=$REMOTE_IMAGE CONTAINER_NAME=$CONTAINER_NAME CONTAINER_PORT=$CONTAINER_PORT"
    only:
        - stg
    when: manual
    tags:
        - frontend


生产环境-灰度发布: # 只发布一台看看有没有问题
    type: deploy
    script:
        - echo "开始编译新镜像：${IMAGE} ..."
        - docker build -t $IMAGE .
        - docker tag $IMAGE $REMOTE_IMAGE
        - docker push $REMOTE_IMAGE
        - echo '新镜像已生成，开始部署到各目标机上...'
        - ansible-playbook deploy/deploy.yml -i deploy/hosts --extra-vars "ENV=prod REMOTE_IMAGE=$REMOTE_IMAGE CONTAINER_NAME=$CONTAINER_NAME CONTAINER_PORT=$CONTAINER_PORT"
    only:
        - prod
    when: manual
    tags:
        - frontend


生产环境-全量发布: # 全量发布所有的生产服务器
    type: deploy
    script:
        - echo "开始编译新镜像：${IMAGE} ..."
        - docker build -t $IMAGE .
        - docker tag $IMAGE $REMOTE_IMAGE
        - docker push $REMOTE_IMAGE
        - echo '新镜像已生成，开始部署到各目标机上...'
        - ansible-playbook deploy/deploy.yml -i deploy/prod-hosts --extra-vars "ENV=prod REMOTE_IMAGE=$REMOTE_IMAGE CONTAINER_NAME=$CONTAINER_NAME CONTAINER_PORT=$CONTAINER_PORT"
    only:
        - prod
    when: manual
    tags:
        - frontend
