---
- hosts: "{{ENV | default('test')}}"
  remote_user: developer
  tasks:
  - name: 拉取远程镜像
    command: docker pull {{REMOTE_IMAGE}}
  - name: 停止旧的docker容器
    command: docker stop {{CONTAINER_NAME}}
    ignore_errors: True
  - name: 移除旧的docker容器
    command: docker rm {{CONTAINER_NAME}}
    ignore_errors: True
  - name: 运行起新的docker容器
    command: docker run -d --restart=always --name {{CONTAINER_NAME}} -p {{CONTAINER_PORT}}:80 {{REMOTE_IMAGE}}