---
- hosts: develop 
  remote_user: developer
  tasks:
  - name: 拉取远程镜像
    command: docker pull {{REMOTE_IMAGE}}
  - name: 停止并移除旧的容器
    command: docker stop {{CONTAINER_NAME}}
    ignore_errors: True
  - name: remove previous version container
    command: docker rm {{CONTAINER_NAME}}
    ignore_errors: True
  - name: run new container
    command: docker run -d --restart=always --name {{CONTAINER_NAME}} -p {{CONTAINER_PORT}}:80 {{REMOTE_IMAGE}}